use mkdocs

diff --git a/.github/workflows/_generate-docs.yml b/.github/workflows/_generate-docs.yml
--- a/.github/workflows/_generate-docs.yml
+++ b/.github/workflows/_generate-docs.yml
@@ -10,11 +10,20 @@ jobs:
         uses: actions/checkout@v4
       - name: Generate docs with emmylua_doc_cli
         run: |
-          cargo install emmylua_doc_cli
-          emmylua_doc_cli --input . --output ./docs
-      - name: Deploy
-        #if: ${{ github.event_name == 'push' }}
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./docs
+          URL=$(curl -s https://api.github.com/repos/EmmyLuaLs/emmylua-analyzer-rust/releases/latest | jq -r '.assets[] | select(.name? | match("emmylua_doc_cli-linux-x64.tar.gz$")) | .browser_download_url')
+          if [ -n "$URL" ]; then
+            curl -L "$URL" -o emmylua_doc_cli-linux-x64.tar.gz
+          else
+            echo "::error:: ❌ File not found in latest release."
+            exit 1
+          fi
+          
+          tar -xzf emmylua_doc_cli-linux-x64.tar.gz
+          chmod +x emmylua_doc_cli-linux-x64.tar.gz
+
+          ./emmylua_doc_cli --input . --output ./docs
+      - name: Deploy docs
+        uses: mhausenblas/mkdocs-deploy-gh-pages@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          CONFIG_FILE: docs/mkdocs.yml
